### ISSUE TITLE
Contribute to rhai org?

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai_rustler#168]
Hi, I'm wondering if you would be interested to contribute this into the rhai org.

**Comment by fabriziosestito** [comment]
Hi, awesome! Let's proceed.

**Comment by fabriziosestito** [comment]
I need to be a member of the org to transfer the repo. I'd like to remain the admin of this repository if possible.

**Comment by schungx** [comment]
OK, I've sent you a member invitation.  Let me know if you need anything else.

**Comment by fabriziosestito** [comment]
I've migrated the repo under the rhaiscript organization, but I miss the admin permissions.
Also, we might want to create a rhai https://hex.pm/ account and transfer the elixir package there as well.

**Comment by schungx** [comment]
> I've migrated the repo under the rhaiscript organization, but I miss the admin permissions. Also, we might want to create a rhai https://hex.pm/ account and transfer the elixir package there as well.

I'll make you admin right away.

**Comment by schungx** [comment]
Do you think it is possible to rename the repo to `rhai-rustler` to be consistent with naming?

**Comment by fabriziosestito** [comment]
I think it would be confusing since `rhai_rustler` is the name of the elixir package as well. Elixir packages have usually snake cased names:
https://hex.pm/packages

**Comment by schungx** [comment]
That's fine with me!  OK closing this.  Thanks for your contribution!
